apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: client
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
      - env:
        - name: DEBUG
          value: "1"
        - name: IRC_CHANNEL
          value: oslohackerspace
        - name: IRC_HOST
          value: chat.freenode.net
        - name: IRC_NICK
          value: hackeriet-jss
        - name: IRC_PORT
          value: "6667"
        - name: IRC_REALNAME
          value: github.com/hackeriet/irc-http
        image: irc
        imagePullPolicy: "Never"
        name: client
        ports:
        - containerPort: 3000
          hostIP: 127.0.0.1
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
